name: esmac-2024-seminar
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - sphinx
  - ipykernel
  - jupyter
  - ipywidgets
  - plotly
  - pyomeca
  - ezc3d
  - kineticstoolkit
  - pip:
    - kielmat
    - gaitmap
    - gaitmap_mad
    - vqf
